#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Fc.CustomContainer.Sample/Fc.CustomContainer.Sample.csproj", "Fc.CustomContainer.Sample/"]
RUN dotnet restore "Fc.CustomContainer.Sample/Fc.CustomContainer.Sample.csproj"
COPY . .
WORKDIR "/src/Fc.CustomContainer.Sample"
RUN dotnet build "Fc.CustomContainer.Sample.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Fc.CustomContainer.Sample.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Fc.CustomContainer.Sample.dll"]